# Generated by Django 4.2.7 on 2023-11-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Gener', models.CharField(max_length=255)),
                ('PerfilPhoto', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('Ubication', models.CharField(blank=True, max_length=100, null=True)),
                ('Biography', models.TextField(blank=True, null=True)),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('PublicationID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('PublicationDate', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('SendDate', models.DateTimeField(auto_now_add=True)),
                ('Check', models.BooleanField(default=False)),
                ('Receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='app.users')),
                ('Transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('ComentID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('ComentDate', models.DateTimeField(auto_now_add=True)),
                ('Publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publication')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
