# Generated by Django 4.0 on 2023-12-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customuser_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
