# Generated by Django 4.0 on 2023-12-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_post_content_post_bible_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pinned_comment',
        ),
    ]
